_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 935d22dc-0349-41ce-8dea-62417dfadf01
name: WhiskeyDex
mail: hello@whiskeydex.com
slogan: ''
page:
  403: /user/login
  404: ''
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: re-reply@whiskeydex.com
